Fail the build if dev is labelled as latest

diff --git a/.github/workflows/docs_build.yml b/.github/workflows/docs_build.yml
--- a/.github/workflows/docs_build.yml
+++ b/.github/workflows/docs_build.yml
@@ -13,6 +13,12 @@ jobs:
     permissions:
       contents: write
     steps:
+      - name: Check inputs
+        run: |
+          if [ -z "${{ inputs.version }}" ] && ${{ inputs.latest }}; then
+            echo "Cannot label dev build as latest. Failing the job."
+            exit 1
+          fi
       - name: Checkout
         uses: actions/checkout@v3.3.0
         with:
@@ -66,7 +72,7 @@ jobs:
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
           git_hash=$(git rev-parse --short HEAD)
-          mike deploy ${{inputs.version || 'dev'}} ${{inputs.latest && inputs.version && 'latest' || ''}} --update-aliases --branch docs-pages ${{inputs.deploy && '--push' || ''}} --message "Deploying docs: ${{inputs.version || 'dev'}} $git_hash ${{inputs.latest && inputs.version && '[latest]' || ''}}"
+          mike deploy ${{inputs.version || 'dev'}} ${{inputs.latest && 'latest' || ''}} --update-aliases --branch docs-pages ${{inputs.deploy && '--push' || ''}} --message "Deploying docs: ${{inputs.version || 'dev'}} $git_hash ${{inputs.latest && '[latest]' || ''}}"
           mike set-default latest --branch docs-pages ${{inputs.deploy && '--push' || ''}}
 
       - name: List docs versions after build
