check latest version

diff --git a/.github/workflows/execute_installation_tests_v3.yml b/.github/workflows/execute_installation_tests_v3.yml
--- a/.github/workflows/execute_installation_tests_v3.yml
+++ b/.github/workflows/execute_installation_tests_v3.yml
@@ -22,7 +22,7 @@ on:
         default: '3.13'
         type: choice
         options:
-          - all
+          - "all"
           - "3.7"
           - "3.8"
           - "3.9"
@@ -30,6 +30,19 @@ on:
           - "3.11"
           - "3.12"
           - "3.13"
+      arcticdb_version:
+        description: 'ArcticDB version to test'
+        required: false
+        default: 'latest'
+        type: choice
+        options:
+          - "latest"
+          - "5.3.3"
+          - "5.2.6"
+          - "5.1.2"
+          - "5.0.0"
+          - "4.4.7"
+
 jobs:
 
   test:
@@ -56,6 +69,7 @@ jobs:
       fail-fast: false  
     env:
       conda_file: "environment_unix.yml"
+      arcticdb_version: ${{ inputs.arcticdb_version || 'latest' }}
 
     steps:
 
@@ -72,6 +86,20 @@ jobs:
       shell: bash -l {0}
       run: |
         python -m pip install --upgrade pip
+
+        VER=${{ env.arcticdb_version }}
+
+        if [[ "$VER" == "latest" ]]; then
+          echo "Installing the latest version..."
+          pip install your_module_name    
+        elif [[ -n "$VER" ]]; then
+          echo "Installing version $VER..."
+          pip install your_module_name==$VER  
+        else
+          echo "Environment variable is not set or invalid!"
+          exit 1  
+        fi        
+
         pip install arcticdb
         pip install wheel
         pip install setuptools
@@ -97,7 +125,19 @@ jobs:
       shell: bash -l {0}
       run: |
           micromamba activate arcticdb
-          micromamba install -c conda-forge arcticdb
+
+          VER=${{ env.arcticdb_version }}
+          
+          if [[ "$VER" == "latest" ]]; then
+            echo "Installing the latest version..."
+            pip install your_module_name    
+          elif [[ -n "$VER" ]]; then
+            echo "Installing version $VER..."
+            pip install your_module_name==$VER  
+          else
+            echo "Environment variable is not set or invalid!"
+            exit 1  
+          fi        
   
     - name: Set persistent storage variables
       if: always()
